58 privatumo politika
Cheezco/Max pull request #16
Opened 2022-03-31 20:02 UTC by augis1123

2022-04-02 07:22 UTC, Cheezco requested changes
Kodas atrodo neblogai, tačiau reiktu patvarkyti vietas kur yra komentarai, šiek tiek pakeisti css klasių pavadinimus, kad jų paskirtis būtų aiškesnė, ir sutvarkyti tarpus ir indentacija.

2022-04-02 07:22 UTC, Cheezco commented on pages/privacy.js
> +import styles from "../styles/pages/informationPage/information.module.css";
Atskiriem puslapiam reikia kurti naujus css dokumentus.

2022-04-02 07:22 UTC, Cheezco commented on styles/pages/informationPage/information.module.css
> +    font-size: 1em;
Default teksto dydis yra 1em, tai atskirai to nustatyti nereikia.

2022-04-02 19:32 UTC, augis1123 commented
Pataisiau klaidas tikriausiai visas

2022-04-03 11:05 UTC, Cheezco approved these changes

2022-04-03 11:06 UTC, merged