Max 47 sukurti siuntimų puslapį
Cheezco/Max pull request #18
Opened 2022-04-04 07:10 UTC by Mindzks

Kolkas sukurtas tik atskiras siuntimų puslapis, ne toks kur buvo numatytas pradiniame variante. Pridėta sidebar nuoroda į siuntimus. Taip pat sutvarkiau linkus 'privatumo politika' ir 'kontaktai', kad pas paspaudus ant jų iš karto numestų i reikiamą puslapį iš pgr. lango

2022-04-04 11:21 UTC, Cheezco requested changes
Šiaip kodas tikrai neblogas, tik reiktu patvarkyti diagnosis.js ir sendings.js. Prie diagnosis.js yra komentarai ir tas vietas reiktu patvarktyti. Tą patį reikia patvarkyti ir sendings.js.

2022-04-04 11:21 UTC, Cheezco commented on pages/diagnosis.js
> +import * as React from "react";
Visko geriau yra neimportuoti. Šiuo atveju jei neklystu užtektu importuoti tik useState.

2022-04-04 11:21 UTC, Cheezco commented on pages/diagnosis.js
> +import styles from "../styles/pages/certificatePage/certificate.module.css";
Atskiriem files reikia kurti naujus css dokumentus.

2022-04-04 11:21 UTC, Cheezco commented on pages/diagnosis.js
> +export default function diagnosis() {
Puslapių ir components funkcijų pavadinimai turi prasidėti iš didžiosios raidės.

2022-04-04 11:21 UTC, Cheezco commented on pages/diagnosis.js
> +                {rows
Prieš naudojant array reiktu patikrinti ar jis nėra undefined ar null. Jei taip gautusi, kad jis yra undefined ar null visas puslapis nebeveiks.

2022-04-04 11:21 UTC, Cheezco commented on pages/diagnosis.js
> +                        {columns.map((column) => {
Taip pat kaip ir su rows reikia patikrinti ar columns nėra undefined ar null.

2022-04-04 11:21 UTC, Cheezco commented on pages/diagnosis.js
> +      <Box className={styles.table_center}>
Kadangi naudojame css modules, tai css klasių pavadinimams reiktu naudoti camelCase.

2022-04-20 14:15 UTC, Mindzks commented on pages/diagnosis.js
> +import * as React from "react";
Tiksliai nepamenu bet su useStates man atrodo lūždavo

2022-04-20 14:16 UTC, Mindzks commented on pages/diagnosis.js
> +import styles from "../styles/pages/certificatePage/certificate.module.css";
Tobulinant puslapį perdarysiu css diagnosis puslapiui

2022-04-20 14:25 UTC, Mindzks commented on pages/diagnosis.js
> +                {rows
Nelabai moku tai padaryt nes copy paste dariau iš intiko

2022-04-20 14:26 UTC, Mindzks commented on pages/diagnosis.js
> +                        {columns.map((column) => {
same as before. Copy paste dariau, jei parašytum žinočiau kaip daryti :D

2022-04-22 08:21 UTC, augis1123 approved these changes

2022-04-22 11:51 UTC, Cheezco approved these changes

2022-04-22 16:12 UTC, merged